server:
  realmName: http://127.0.0.1
  port: 1016
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: bookcase
  userName: root
  password: 123456
  charset: utf8
  loc: Asia/Shanghai
superAdmin:
  teacherId: superAdmin
  name: superAdmin
  password: 123456
applet:
  appID: wxea179169274cc790
  appSecret: 6a9c4459bad553a84fd215e5d5c753c1
slid:
  img1: /resource/image/slid/bg1.png
  img2: /resource/image/slid/bg1.png
  img3: /resource/image/slid/bg1.png
